baseurl = "https://olehmarshev.com/"
title = "Oleh Marshev"
copyright = "Copyright &copy; 2018 - Oleh Marshev"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = "olmar"
    gitlab = ""
    linkedin = "olegmarshev"
    facebook = ""
    twitter = "OlegMarshev"
    instagram = ""

[params]
    tagline = "Some thoughts"
