baseURL = "https://olehmarshev.com/"
theme = "cocoa-eh"

builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = ""
title = "Oleh Marshev"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Some thoughts"
copyright = "Copyright © 2018"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
latestpostcount = 5
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "olmar"
email = "oleh.marshev@gmail.com"
linkedin = "olegmarshev"
twitter = "OlegMarshev"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
