baseurl = "https://olehmarshev.com/"
title = "Oleh Marshev"
theme = "coder"

[params] # theme parameters
    author = "Oleh Marshev" # author's name
    info = "Some thoughts" # author's job title or info
    description = "John Doe's personal website" # site description
    keywords = "blog,developer,engineering" # site keywords

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/olmar/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/OlegMarshev/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/olegmarshev/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"

#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"
